sudo: required

language: php
php:
  - '5.6'
  - '7.0'

install:
  - composer install --no-scripts

script:
  - ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .

notifications:
  email: false
  slack: keboola:UwKWVoCQWAcgvlMDK1q1RMxA
