sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose -v
  - cp .env.dist .env
  - docker-compose build app
script:
  - docker-compose run --rm app ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: I9KAt7ldd6uq6CcQu6wAw/3QOSK/pU/fjWQAj9ADGSzaZbIi/nkZJI/USgsevyElfoXJ38frvjUuP4hYjwUPqpYFziRrJZUn4OIaCcGqZQt0P/Z/XRo8JtaU9zcRSQfrvN3Xcy87Kpj1W39Qu+qppq7CfjuvhI4uEv8NGNEDi3ZvaU0nG9CqNBFVykM50z0NRbAPlDvkEjSv2ljZRAEz8PvRnufVQD06+90Zx0pN9qkmdf/jmgqgq2I//79JaX30yjV6zpFFg5D9eyQnkwfeIn0SBour/lnQEtHBFy2iYSo7fmYBHA+LqZ6/McIQyrQV1oiT9BFdw48S9DfBDerGOKFjWFChoJmBa8ipKsOLnjMJRyHzOAlxehM05KJ+eiwivpsyevHp5KT998HUy0g/32+SDld0BK9GP/iwkaSVtOfSCZhnVVMVGD9Jm734IVx4QZPlxgzHV6ffGgxouFXFjxJYqhxrmBS3UwI9kNzWcwUksPIA5FTxLub7VSRMMwxolSGYaZVjhQ9Hikz6bG1STk49fKmR4rVV70EIs2Z2zlIRjgBFW273wCFyHP/VP2Ur2Fo3m2msOBZzzRhQJDompmsRbKNuyM/o4fKA+Si39OjSSjdNxQ5axe0B1PiSMFTiBDEd0lAr5PYcvBpF2PdEcFZnjLdOcP1FS7v5X3euun8=
