version: '2'
services:
  app:
    build: .
    image: keboola/cli-utils
    tty: true
    stdin_open: true
    command: php cli.php

  dev:
    image: keboola/cli-utils
    volumes:
      - ./:/code
    working_dir: /code
    env_file:
        - .env
    command: >
       sh -c '
       composer install
       && php cli.php
       '

