name: Build

on:
  push

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare env
      run: cp .env.dist .env

    - name: Build container
      run: docker-compose build app

    - name: Run tests
      run: docker-compose run --rm app ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .

    - name: Push
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker login -u=keboolacipush -p="$DOCKERHUB_TOKEN"
        docker tag keboola/cli-utils keboola/cli-utils:$GITHUB_REF_NAME
        docker tag keboola/cli-utils keboola/cli-utils:latest
        docker push keboola/cli-utils:$GITHUB_REF_NAME
        docker push keboola/cli-utils:latest

